import React, { useState } from 'react';
import { useLanguage } from '../../context/LanguageContext';
import { useContractors } from '../../context/ContractorsContext';
import { ITPItem } from '../../context/ITPContext';
import styles from './ITP.module.css';

export interface ITPDetailModalProps {
    itpId: string;
    existingItem?: ITPItem;
    onSave: (updates: Partial<ITPItem>) => void;
    onClose: () => void;
}

export const ITPDetailModal: React.FC<ITPDetailModalProps> = ({ itpId, existingItem, onSave, onClose }) => {
    const { t } = useLanguage();
    const { getActiveContractors } = useContractors();
    const REV_OPTIONS = ['Rev1.0', 'Rev2.0', 'Rev3.0', 'Rev4.0'];
    const [formData, setFormData] = useState<Partial<ITPItem>>({
        vendor: existingItem?.vendor || '',
        referenceNo: existingItem?.referenceNo || '',  // 由後端自動產生
        description: existingItem?.description || '',
        rev: existingItem?.rev || 'Rev1.0',
        submit: existingItem?.submit || '',
        status: existingItem?.status || 'Pending',
        remark: existingItem?.remark || '',
        submissionDate: existingItem?.submissionDate || new Date().toISOString().split('T')[0],
    });

    const [errors, setErrors] = useState<{ [key: string]: string }>({});
    const [revMode, setRevMode] = useState<'select' | 'custom'>(() => {
        const currentRev = existingItem?.rev;
        if (currentRev && !REV_OPTIONS.includes(currentRev)) {
            return 'custom';
        }
        return 'select';
    });

    const handleFieldChange = (field: keyof ITPItem, value: string) => {
        setFormData(prev => ({ ...prev, [field]: value }));
        if (errors[field]) {
            setErrors(prev => ({ ...prev, [field]: '' }));
        }
    };

    const handleDateButton = (field: keyof ITPItem) => {
        const today = new Date();
        const dateStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}_`;
        setFormData(prev => ({
            ...prev,
            [field]: prev[field] ? `${prev[field]}\n${dateStr}` : dateStr
        }));
    };

    const validate = () => {
        const newErrors: { [key: string]: string } = {};
        if (!formData.vendor) newErrors.vendor = 'Contractor is required';

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    const handleSave = () => {
        if (validate()) {
            onSave(formData);
            // onClose is handled by parent after async operation
        }
    };

    return (
        <div className={styles.modalOverlay}>
            <div className={styles.modalContent} onClick={(e) => e.stopPropagation()}>
                <div className={styles.modalHeader}>
                    <h2>{existingItem ? t('itp.editTitle') : t('itp.addTitle')}</h2>
                    <button className={styles.closeButton} onClick={onClose}>×</button>
                </div>
                <div className={styles.modalBody}>
                    <p className={styles.formRequiredHint}>{t('form.requiredHint')}</p>
                    <div className={styles.formSections}>
                        <div className={styles.formSection}>
                            <h3 className={styles.sectionTitle}>{t('itp.infoSection')}</h3>
                            <div className={styles.formGrid}>
                                <div className={styles.formGroup}>
                                    <label>{t('itp.referenceNo')}</label>
                                    <input
                                        type="text"
                                        className={styles.formInput}
                                        value={formData.referenceNo || t('form.autoGenerated')}
                                        readOnly
                                        style={{ backgroundColor: '#D9D9D9', cursor: 'not-allowed', color: formData.referenceNo ? '#000000' : '#666666' }}
                                    />
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('itp.description')}</label>
                                    <input
                                        type="text"
                                        className={styles.formInput}
                                        value={formData.description || ''}
                                        onChange={(e) => handleFieldChange('description', e.target.value)}
                                    />
                                </div>
                                <div className={styles.formGroup}>
                                    <label className={styles.requiredLabel}>{t('itp.vendor')}</label>
                                    <select
                                        className={`${styles.formSelect} ${errors.vendor ? styles.errorInput : ''}`}
                                        value={formData.vendor || ''}
                                        onChange={(e) => handleFieldChange('vendor', e.target.value)}
                                    >
                                        <option value="">{t('itp.selectContractor')}</option>
                                        {getActiveContractors().map((contractor) => (
                                            <option key={contractor.id} value={contractor.name}>
                                                {contractor.name}
                                            </option>
                                        ))}
                                    </select>
                                    {errors.vendor && <span className={styles.errorMessage}>{errors.vendor}</span>}
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('itp.submissionDate')}</label>
                                    <input
                                        type="date"
                                        className={styles.formInput}
                                        value={formData.submissionDate || ''}
                                        onChange={(e) => handleFieldChange('submissionDate', e.target.value)}
                                    />
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('itp.rev')}</label>
                                    {revMode === 'select' && (
                                        <select
                                            className={styles.formSelect}
                                            value={REV_OPTIONS.includes(formData.rev || '') ? formData.rev : 'Rev1.0'}
                                            onChange={(e) => {
                                                const value = e.target.value;
                                                if (value === 'custom') {
                                                    setRevMode('custom');
                                                    handleFieldChange('rev', '');
                                                } else {
                                                    setRevMode('select');
                                                    handleFieldChange('rev', value);
                                                }
                                            }}
                                        >
                                            {REV_OPTIONS.map((r) => (
                                                <option key={r} value={r}>{r}</option>
                                            ))}
                                            <option value="custom">{t('itp.revSelectCustom')}</option>
                                        </select>
                                    )}
                                    {revMode === 'custom' && (
                                        <input
                                            type="text"
                                            className={styles.formInput}
                                            value={formData.rev || ''}
                                            onChange={(e) => handleFieldChange('rev', e.target.value)}
                                            placeholder={t('itp.revPlaceholder')}
                                        />
                                    )}
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('itp.status')}</label>
                                    <select
                                        className={styles.formSelect}
                                        value={formData.status || 'Pending'}
                                        onChange={(e) => handleFieldChange('status', e.target.value)}
                                    >
                                        <option value="Approved with comments">Approved with comments</option>
                                        <option value="Revise & Resubmit">Revise & Resubmit</option>
                                        <option value="Rejected">Rejected</option>
                                        <option value="Pending">Pending</option>
                                        <option value="No submit">No submit</option>
                                        <option value="Void">Void</option>
                                    </select>
                                </div>
                                <div className={styles.formGroupFull}>
                                    <div className={styles.labelWithButton}>
                                        <label className={styles.optionalLabel}>{t('common.remark')}</label>
                                        <button
                                            type="button"
                                            className={styles.tbcButton}
                                            onClick={() => handleDateButton('remark')}
                                        >
                                            {t('common.addDate')}
                                        </button>
                                    </div>
                                    <textarea
                                        className={styles.formTextarea}
                                        value={formData.remark || ''}
                                        onChange={(e) => handleFieldChange('remark', e.target.value)}
                                        rows={3}
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={styles.modalActions}>
                    <button className={styles.saveButton} onClick={handleSave}>
                        {t('common.save')}
                    </button>
                    <button className={styles.cancelButton} onClick={onClose}>
                        {t('common.cancel')}
                    </button>
                </div>
            </div>
        </div>
    );
};

export interface ITPDetailsViewModalProps {
    itpId: string;
    itpItem?: ITPItem;
    onClose: () => void;
}

export const ITPDetailsViewModal: React.FC<ITPDetailsViewModalProps> = ({ itpId, itpItem, onClose }) => {
    const { t } = useLanguage();
    const handlePrint = () => {
        window.print();
    };

    if (!itpItem) {
        return null;
    }

    return (
        <div className={styles.modalOverlay}>
            <div className={styles.modalContent} onClick={(e) => e.stopPropagation()}>
                <div className={styles.modalHeader}>
                    <h2>{t('itp.detail.title')}</h2>
                    <button className={styles.closeButton} onClick={onClose}>×</button>
                </div>
                <div className={styles.modalBody}>
                    <div className={styles.formSections}>
                        <div className={styles.formSection}>
                            <h3 className={styles.sectionTitle}>{t('itp.infoSection')}</h3>
                            <div className={styles.formGrid}>
                                <div className={styles.formGroup}>
                                    <label>{t('itp.referenceNo')}</label>
                                    <div className={styles.readOnlyField}>{itpItem.referenceNo || '-'}</div>
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('itp.status')}</label>
                                    <div className={styles.readOnlyField}>{itpItem.status || '-'}</div>
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('itp.vendor')}</label>
                                    <div className={styles.readOnlyField}>{itpItem.vendor || '-'}</div>
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('itp.description')}</label>
                                    <div className={styles.readOnlyField}>{itpItem.description || '-'}</div>
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('itp.rev')}</label>
                                    <div className={styles.readOnlyField}>{itpItem.rev || '-'}</div>
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('itp.submissionDate')}</label>
                                    <div className={styles.readOnlyField}>{itpItem.submissionDate || '-'}</div>
                                </div>
                                {itpItem.remark && (
                                    <div className={styles.formGroupFull}>
                                        <label>{t('common.remark')}</label>
                                        <div className={styles.readOnlyField}>{itpItem.remark}</div>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
                <div className={styles.modalActions}>
                    <button className={styles.printButton} onClick={handlePrint}>
                        {t('common.print')}
                    </button>
                    <button className={styles.cancelButton} onClick={onClose}>
                        {t('common.close')}
                    </button>
                </div>
            </div>
        </div>
    );
};
